#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

declare -A OS_ARCH_ARG

OS_PLATFORM_ARG=(linux)
OS_ARCH_ARG[linux]="amd64"
PKG="k8s.io/ingress-nginx"

if [ -n "$CROSS" ]; then
    rm -rf bin/*
    mkdir -p bin
    for OS in ${OS_PLATFORM_ARG[@]}; do
        for ARCH in ${OS_ARCH_ARG[${OS}]}; do
            OUTPUT_BIN="bin/$OS/$ARCH/nginx-ingress-controller"
            echo "Building binary for $OS/$ARCH..."
            GOARCH=$ARCH GOOS=$OS CGO_ENABLED=0 go build \
                -a -installsuffix cgo \
                -ldflags="-s -w -X ${PKG}/version.RELEASE=${TAG} -X ${PKG}/version.COMMIT=${COMMIT} -X ${PKG}/version.REPO=${REPO_INFO}" \
                -o ${OUTPUT_BIN} ${PKG}/cmd/nginx
        done
    done
fi
